database_driver:
    type: text
    default: pdo_mysql
    required: false
database_path:
    type: text
    default: null
    required: false
database_host:
    type: text
    default: localhoststs
    required: true
database_port:
    type: integer
    default: "3006"
    required: true
