bootstrap.yml:
    filepath_for_config: 'asdasdasd'
    parameters:
        type: title
        title-name: Parameters
        children:
            testfeld:
                type: field
                field-type: text
                field-name: testfeld
