bootstrap.yml:
    parameters:
        type: title
        childs:
            ggm.theming.active_theme:
                type: text
                default: '~'
            ggm.bootstrap.config:
                type: title
                childs:
                    ggmArticleBundle:
                        type: title
                        childs:
                            enabled:
                                type: boolean
                                default: false
                            root:
                                type: boolean
                                default: false
                            prefix:
                                type: text
                                default: a
                            class:
                                type: text
                                default: 'ggm\ArticleBundle\ggmArticleBundle'
                ggmClassifiedAdBundle:
                    type: title
                    childs:
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: cad
                        class:
                            type: text
                            default: 'ggm\ClassifiedAdBundle\ggmClassifiedAdBundle'
                ggmJobAdBundle:
                    type: title
                    childs:
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: jobs
                        class:
                            type: text
                            default: 'ggm\JobAdBundle\ggmJobAdBundle'
                ggmNewsAgencyBundle:
                    type: title
                    childs:
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: news-agency
                        class:
                            type: text
                            default: 'ggm\NewsAgencyBundle\ggmNewsAgencyBundle'
                ggmEventCalendarBundle:
                    type: title
                    childs:
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: event
                        class:
                            type: text
                            default: 'ggm\EventCalendarBundle\ggmEventCalendarBundle'
                ggmCustomerBundle:
                    type: title
                    childs:
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: null
                        class:
                            type: text
                            default: '$ggm.theming.active_theme$\CustomerBundle\CustomerBundle'
