bootstrap.yml:
    filepath_for_config: 'app/config/bootstrap.yml'
    parameters:
        type: title 
        title-name: 'Parameters' 
        childs:
            ggm.theming.active_theme: 
                type: field
                field-type: text
                field-default: ~
                field-name: active_theme
                field-constraints:
                    0:
                        constraint-name: Length
                        constraint-options:
                            min: 5
                            max: 30
                            minMessage: 'Eingabe zu kurz'
                            maxMessage: 'Eingabe zu lang'
                    1:
                        constraint-name: NotBlank
                        constraint-options:
            ggm.bootstrap.config:
                type: title 
                title-name: 'Bootstrap Config' 
                childs:
                    ggmArticleBundle:    
                        type: title 
                        title-name: 'Article Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default: a
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\ArticleBundle\ggmArticleBundle'
                                field-name: class
                    ggmClassifiedAdBundle:
                        type: title 
                        title-name: 'Classified Ad Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default: cad
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\ClassifiedAdBundle\ggmClassifiedAdBundle'
                                field-name: class
                    ggmJobAdBundle:
                        type: title 
                        title-name: 'Job Ad Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default: jobs
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\JobAdBundle\ggmJobAdBundle'
                                field-name: class
                    ggmNewsAgencyBundle:
                        type: title 
                        title-name: 'News Agency Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default: news-agency
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\NewsAgencyBundle\ggmNewsAgencyBundle'
                                field-name: class
                    ggmEventCalendarBundle:
                        type: title 
                        title-name: 'Event Calendar Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default: event
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\EventCalendarBundle\ggmEventCalendarBundle'
                                field-name: class
                    ggmCustomerBundle:
                        type: title 
                        title-name: 'Customer Bundle'
                        childs:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                type: field
                                field-type: text
                                field-default:
                                field-name: prefix
                            class:
                                type: field
                                field-type: text
                                field-default: '$ggm.theming.active_theme$\CustomerBundle\CustomerBundle'
                                field-name: class
