bootstrap.yml:
    filepath_for_config: 'app/config/parameters.yml'
    parameters:
        stage: 1
        type: title
        childs:
            ggm.theming.active_theme:
                stage: 2
                type: field
                field-type: text
                field-default: '~'
                field-name: active_theme
            ggm.bootstrap.config:
                stage: 2
                type: title
                childs:
                    ggmArticleBundle:
                        stage: 3
                        type: title
                        childs:
                            enabled:
                                stage: 4
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: enabled
                            root:
                                stage: 4
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: root
                            prefix:
                                stage: 4
                                type: field
                                field-type: text
                                field-default: a
                                field-name: prefix
                            class:
                                stage: 4
                                type: field
                                field-type: text
                                field-default: 'ggm\ArticleBundle\ggmArticleBundle'
                                field-name: class
                    ggmClassifiedAdBundle:
                        stage: 3
                        type: title
                        childs:
                                enabled:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: enabled
                                root:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: root
                                prefix:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: cad
                                    field-name: prefix
                                class:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: 'ggm\ClassifiedAdBundle\ggmClassifiedAdBundle'
                                    field-name: class
                    ggmJobAdBundle:
                        stage: 3
                        type: title
                        childs:
                                enabled:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: enabled
                                root:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: root
                                prefix:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: jobs
                                    field-name: prefix
                                class:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: 'ggm\JobAdBundle\ggmJobAdBundle'
                                    field-name: class
                    ggmNewsAgencyBundle:
                        stage: 3
                        type: title
                        childs:
                                enabled:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: enabled
                                root:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: root
                                prefix:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: news-agency
                                    field-name: prefix
                                class:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: 'ggm\NewsAgencyBundle\ggmNewsAgencyBundle'
                                    field-name: class
                    ggmEventCalendarBundle:
                        stage: 3
                        type: title
                        childs:
                                enabled:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: enabled
                                root:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: root
                                prefix:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: event
                                    field-name: prefix
                                class:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: 'ggm\EventCalendarBundle\ggmEventCalendarBundle'
                                    field-name: class
                    ggmCustomerBundle:
                        stage: 3
                        type: title
                        childs:
                                enabled:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: enabled
                                root:
                                    stage: 4
                                    type: field
                                    field-type: boolean
                                    field-default: false
                                    field-name: root
                                prefix:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default:
                                    field-name: prefix
                                class:
                                    stage: 4
                                    type: field
                                    field-type: text
                                    field-default: '$ggm.theming.active_theme$\CustomerBundle\CustomerBundle'
                                    field-name: class
