bootstrap.yml:
    parameters:
        ggm.theming.active_theme:
            type: text
            default: '~'
        ggm.bootstrap.config:
            type: title
                ggmArticleBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: a
                        class:
                            type: text
                ggmClassifiedAdBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: cad
                        class:
                            type: text
                ggmJobAdBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: jobs
                        class:
                            type: text
                ggmNewsAgencyBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: news-agency
                        class:
                            type: text
                ggmEventCalendarBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: event
                        class:
                            type: text
                ggmCustomerBundle:
                    type: title
                        enabled:
                            type: boolean
                            default: false
                        root:
                            type: boolean
                            default: false
                        prefix:
                            type: text
                            default: null
                        class:
                            type: text
